### ISSUE TITLE
Invalid dependencies - incompatible history and react-router

### ISSUE THREAD

**Issue by jksdua** [eriknyk/redux-universal-app#1]
Getting this error when trying to `npm install`

``` bash
$ npm i
npm ERR! Linux 3.19.0-42-generic
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "i"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package history@1.17.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router@1.0.2 wants history@1.13.x

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cute/tmp/redux-universal-app/npm-debug.log
```

This fixes the issue:

``` diff
-    "history": "^1.13.1",
+    "history": "~1.13.1",
```

**Comment by eriknyk** [comment]
good catch,
since I get this works, it was working, I think this happens with most recent version on history.

however I just tried using npm 3.3.12 (it is coming with node v5.2) and it worked without problems

**Comment by jksdua** [comment]
Yeh just need to lock in the dependency. That fixes the issue.

On Fri, Dec 25, 2015 at 4:25 AM, Erik notifications@github.com wrote:
good catch,
since I get this works, it was working, I think this happens with most recent
version on history.

—
Reply to this email directly or view it on GitHub
[https://github.com/eriknyk/redux-universal-app/issues/1#issuecomment-167139677] .[https://github.com/notifications/beacon/ABd6s2PW7qEB2UGllEMG9cxEIpdkFA69ks5pTCH-gaJpZM4G6h5M.gif]

**Comment by eriknyk** [comment]
the code and packages version were updated, 
now the example is running using RR 2.0, and redux-simple-router 2.0

see https://github.com/eriknyk/redux-universal-app/commit/3ac2894aaf92e311c5b6f0e04867b78be22cb5c7
