### ISSUE TITLE
Several different initial states?

### ISSUE THREAD

**Issue by selbekk** [eriknyk/redux-universal-app#2]
Hi,

I have several different views (like this example does), but all of them needs different bootstrap data from the database. An example could be `/search/{query}`, which would need to search the database for `{query}`. Another would be `/user/{id}`, where the app would need to look up the user ID before serving the data.

In your (or redux') example, there's only one API call for all requests, no matter which route is requested. How would I go about doing this the best way possible?

**Comment by eriknyk** [comment]
Hi, the primary task for this example was convert the universal example (\* https://github.com/reactjs/redux/tree/master/examples/universal) from official redux examples, to "" Universal + react-router "" example,..

but regarding to your comment you can try something like this, on the routes.js and you can figure out the rest.

```
var routes = {
  path: '/',
  component: App,
  indexRoute: { component: Home },
  childRoutes: [
    { path: 'about', component: About },
    { path: 'home', component: Home },
    { path: 'Counter', component: Counters },
    { 
      path: 'search', component: Search,
      childRoutes: [
          { path: ':query', component: SearchQuery },
      ]
    },
    { 
      path: 'user', component: User,
      childRoutes: [
          { path: ':id', component: UserFormView },
      ]
    },
    { path: '*', component: NotFound }
  ]
};

```

**Comment by selbekk** [comment]
Thanks! :+1:
